const ESTADOS_EXPEDIENTE = {
  BORRADOR: "BORRADOR",
  COTIZACION_GENERADA: "COTIZACION_GENERADA",
  EN_NEGOCIACION: "EN_NEGOCIACION",
  COTIZACION_ACEPTADA: "COTIZACION_ACEPTADA",
  COTIZACION_RECHAZADA: "COTIZACION_RECHAZADA",
  COTIZACION_VENCIDA: "COTIZACION_VENCIDA",
  CANCELADA: "CANCELADA",
  OPERACION_ABIERTA: "OPERACION_ABIERTA",
  COMPRA_FINALIZADA: "COMPRA_FINALIZADA"
};

console.log("Estados de expediente cargados:", ESTADOS_EXPEDIENTE);
